#!/bin/bash
set +x
rm -rf app
mkdir app
mkdir app/src
mkdir app/src/common
uglifyjs index.js -c -m -o app/index.js
for MODULE in api-admin api-user backbone-links site-templates site-deployment-state certs config db manage-sync mc-apiserver mc-main prune
do
    cp src/$MODULE.js app/src/$MODULE.js
#    uglifyjs src/$MODULE.js --toplevel -c -m -o app/src/$MODULE.js
done
for MODULE in amqp kube log protocol util
do
    cp ../common/$MODULE.js app/src/common/$MODULE.js
#    uglifyjs ../common/$MODULE.js --toplevel -c -m -o app/src/common/$MODULE.js
done
