#!/bin/bash
set +x
rm -rf app
mkdir app
mkdir app/src
mkdir app/src/common
uglifyjs index.js -c -m -o app/index.js
for MODULE in ingress links sc-apiserver sc-main site-sync
do
    cp src/$MODULE.js app/src/$MODULE.js
#    uglifyjs src/$MODULE.js --toplevel -c -m -o app/src/$MODULE.js
done
for MODULE in amqp kube protocol log router util
do
    cp ../common/$MODULE.js app/src/common/$MODULE.js
#    uglifyjs ../common/$MODULE.js --toplevel -c -m -o app/src/common/$MODULE.js
done
